name: Branches

# Run this workflow every time a new commit pushed to your repository
on: 
  push:
    branches-ignore:
      - main
jobs:
  show-key-values:
    name: show values of variables
    runs-on: ubuntu-latest

    steps:
      - name: run test command
        run: |
          echo github.event_name: ${{ github.event_name }}
          echo github.ref: ${{ github.ref }}

  call-format-and-lint:
    uses: bpafoshizle/actions/.github/workflows/lint.yml
  
  call-build-docker:
    uses: bpafoshizle/actions/.github/workflows/docker-build.yml
    with:
      platform: 'linux/amd64,linux/arm64'